### PR TITLE
add missing numpy <2 requirement

### PR DESCRIPTION
**Pull request by daylinmorgan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes the missing numpy <2 requirement added for `v1.10.2`. 
Which can be removed in the next release.

### CODE REVIEW

**Comment by jdblischak** [comment]
If this is only to fix the upper bound of the numpy run requirement for an already published version, it might make more sense to submit a [repodata patch](https://conda-forge.org/docs/maintainer/infrastructure/#repodata-patch) instead of building a new version (which also won't prevent someone from installing scanpy 1.10.2 with numpy 2 since the original binary will still exist).

**Comment by daylinmorgan** [comment]
I wasn't aware of that option, thanks for bringing it to my attention. I'll submit a PR over on the repodata patch feedstock.

**Comment by flying-sheep** [comment]
FYI: the next patch will allow use with numpy 2 again, so this should exclusively be a repodata patch and not go into the feedstock.

**Comment by daylinmorgan** [comment]
Repodata patch was merged in https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/792, sorry for the noise.

**Pull request closed without merging**
